backend:
  name: github
  branch: main 
  repo: butzbach-spielt/butzbach-spielt-website
media_folder: "src/img"
media_library:
  name: uploadcare
  config:
    publicKey: 76df8080dfd5c836240b
    imagesOnly: true
public_folder: "/img"
publish_mode: editorial_workflow
collections:
  - name: "card" # Used in routes, e.g., /admin/collections/blog
    description: Diese Elemente werden als Karte auf der Startseite angezeigt.
    label: "Card" # Used in the UI
    folder: "src/cards" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    sortable_fields:
      - "displayOrder"
    fields: # The fields for each document, usually in front matter
      - {label: "Reihenfolge", name: "displayOrder", widget: "number", required: true}
      - {label: "Titel", name: "title", widget: "string", required: true}
      - {label: "Bild", name: "image", widget: "image", allow_multiple: false}
      - {label: "Bild Alt Text", name: "imageAlt", widget: "string", required: true}
      - {label: "Inhalt", name: "body", widget: "markdown"}
  - name: "gallery"
    folder: "src/gallery"
    label: "Gallery" 
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string", required: true}
      - label: "Images"
        name: "images"
        widget: "image"
        media_folder: "img"
        media_library:
          config: 
            multiple: true
        choose_url: false


